const fields = {
    'type': 'type',
    '_type': '_type',
    'name': 'name',
    'ownedElements': 'ownedElements',
    'abstractFiles': 'abstractFiles',
    'dependent': 'dependent',
    'isAbstract': 'isAbstract',
    'description': 'description',
    'documentation': 'documentation',
    'version': 'version',
    'status': 'status',
    'Required': 'Required',
    'Property': 'Property',
    'isID': 'isID',
    'pattern': 'pattern',
    'DataType': 'DataType',
    '_parent': '_parent',
    'cardinality': 'cardinality',
    'navigable': 'navigable',
    'package': 'package',
    'Enum': 'Enum',
    'Relationship': 'Relationship',
    'Operation': 'Operation',
    'Parameter': 'Parameter',
    'source': 'source',
    'target': 'target',
    'association': 'association',
    'class': 'class',
    'from': 'from',
    'to': 'to',
    'Entity': 'Entity',
    'Event': 'Event',
    'interfaceRealization': 'interfaceRealization',
    'generalization': 'generalization',
    'associationClassLink': 'associationClassLink',
    'aggregation': 'aggregation',
    'composition': 'composition',
    'interface': 'interface',
    'value': 'value',
    'tags': 'tags',
    'kind': 'kind',
    'defaultValue': 'defaultValue',
    'resources': 'resources',
    'dataTypes': 'dataTypes',
    'dataType': 'dataType',
    'entities': 'entities',
    'properties': 'properties',
    'relationships': 'relationships',
    'attributes': 'attributes',
    'extra': 'extra',
    'minCardinality': 'minCardinality',
    'maxCardinality': 'maxCardinality',
    'resource': 'resource',
    'reference': 'reference',
    'multiplicity': 'multiplicity',
    'contains' : 'contains',
    'references' : 'references',
    'typeOf' : 'typeOf',
    'end1' : 'end1',
    'end2' : 'end2',
    'codes' : 'codes',
    'code' : 'code',
    'propertyValues' : 'propertyValues',
    'propertyName' : 'propertyName',
    'codeLists' : 'codeLists',
    'literals' : 'literals',
};
module.exports = fields;